---
title: "Difference-in-Difference"
output: 
  pdf_document:
     toc: true
     toc_depth: 2
     fig_width: 6
     fig_height: 3
     fig_caption: true
---

# Basic Idea
Suppose we have two periods: before, $t'$, and after, $t$. Individuals are divided into two groups , one with $D=1$ (experiment group) and one with $D=0$ (control group). At period $t'$, no treatment happens.Everyone's outcome is denoted as $y_{0t'}$. At period $t$, experiment group gets treatment, so they have $y_{1t}$; individuals in control group do not get treatment, so they have $y_{0t}$ 
<p>The logic flow of DID derivation is same as the treatment effect model. We want to estimate the following:
$$E(y_{1t}|x,D=1)- E(y_{0t}|x,D=1)$$
But $E(y_{0t}|x,D=1)$ is not observable! To address this, we do the following algebra:</p>
$$E(y_{1t}|x,D=1)- E(y_{0t}|x,D=1)= E(y_{1t}|x,D=1)-E(y_{0t'}|x,D=1)+E(y_{0t'}|x,D=1)- E(y_{0t}|x,D=1)$$
$$=\left(E(y_{1t}|x,D=1)-E(y_{0t'}|x,D=1)\right)-\left(E(y_{0t}|x,D=1)-E(y_{0t'}|x,D=1)\right) \tag{1}$$

- $E(y_{1t}|x,D=1)-E(y_{0t'}|x,D=1)$ is the total <b>observable</b> change of the outcome variable (from $t'$ to $t$) for individual $x$ in the treatment group. 
- $E(y_{0t}|x,D=1)-E(y_{0t'}|x,D=1)$ is the 'hypothetical' change of the outcome variable as if the individual $x$ in the treatment group do not participate in the treatment. This measure the 'natural' change (i.e., the change if there is no policy treatment) of the outcome for individuals in the treatment group. unobservable!

The total observable change, minus the 'hypothetical' natural change, is the change brought by the treatment, i.e, the effect of the treatment. However, since the 'hypothetical change' is unosbservable, we need to again
 introduce the CIA assumption: 
$$E(y_{0t}-y_{0t'}|x,D)=E(y_{0t}-y_{0t'}|x)$$
i.e., given the $x$, the trend of outcome (i.e., natural change of outcome without any treatment ) is independent of 'whether getting treatment or not'.
Having knowing this, we have 
$$E(y_{0t}-y_{0t'}|x,D=1)=E(y_{0t}-y_{0t'}|x,D=0)$$
The right hand side is observable. Plugging this expression into (1), we have 
$$E(y_{1t}|x,D=1)- E(y_{0t}|x,D=1)=E(y_{1t}-y_{0t'}|x,D=1)- E(y_{0t}-y_{0t'}|x,D=0) \tag{2}$$
Both terms in the right hand side are observable.

# Paremetric Method : Linear regression

## Two Period

Denote $t_0$ and $t_1$ as the period before and after the treatment. We now present how to 'recover' the linear regression specification from (2). 
denote that 
$$E(y_{0t_0}|x,D=0)=\alpha_1$$
i.e., $\alpha_1$ is the level of $y$ for people in the control group before the experiment happens. We next denote that
$$E(y_{0t}|x,D=0)=\alpha_1+\alpha_2$$
$\alpha_2$ denotes the 'natural' change of $y$ without any experiment effects (i.e., the change of $y$ for people in the control group)
Denote that
$$E(y_{0t_0}|x,D=1)=\alpha_1+\alpha_3$$
$\alpha_3$ denotes the difference of $y$ between the control group and the experiment group before the experiment happens. 
Finally denotes that
$$E(y_{1t_1}|x,D=1)=\alpha_1+\alpha_3+\alpha_2 + \alpha_4$$
we can see that the change of $y$ for the people in the experiment group comes from two parts, $\alpha_2$, the natural change of $y$, and $\alpha_4$, the net effect of the treatment.
Therefore we can see that 

- The $\alpha_2$ appears only when the people is after the experiment. denote $G=1(0)$ as after (before) the treatment. the $\alpha_2$ is thus the coefficient of $G$. 

- The $\alpha_3$ appears only when the people is at experiment group. Denote $D=1(0)$ as in (not in) the treatment group. The $\alpha_3$ is thus the coefficient of $D$.

- The $\alpha_4$ appears only the people is at experiment group, and the is after experiment. The $\alpha_4$ is thus the coefficient of $G*D$.

Finally the model can be written as
$$y_{it}= \alpha_1+\alpha_2 G_t + \alpha_3 D_{it} + \alpha_4 G_t*D_{it} + \gamma X_i+ \epsilon_{it}$$
But remember, when we have panel data structure, we always need to care about the cluster problems: The data points in the same cluster may have correlated errors. In the DID setting, each individual contains two data points, which may have correlated error term. Heteroskedasticity problem may also exist: it is possible that a larger individual may have higher variance of error term. Here, the 'cluster' is each individual.

As we know, three methods can deal with this situation: use robust error; add cluster-specific fixed effect; add cluster-specific random effect. Using robust error and cluster-specific random effect can deal with both within-cluster correlation and cluster-specific heteroskedasticity, while cluster-specific fixed effect only deals with within-cluster correlation.

For example, we assume cluster-specific intercept (in our case, individual-specific intercept):
$$y_{it}= \beta_{i}+\alpha_2 G_t + \alpha_3 D_{i} + \alpha_4 G_t*D_{i} + \gamma X_i +\epsilon_{it}$$

## Multiple-period
Sometimes, we may not always have the perfect two-period setting: for individuals in the treatment group, the timing of getting treatment may be different. Therefore we need a multiple-period DID setting. 

Notice that we can rewrite the regression specification for two-period model as:
$$y_{it} = \alpha_0 + \alpha_2 G_t + \alpha_3 D_{i} + \alpha_4 S_{it} + \gamma X_{it} +\epsilon_{it}, \tag{1} $$
in which 
$$S_{it} = 
\begin{cases}
1, \quad D_i = 1 \quad \& \quad t=t_1  \\
0, \quad otherwise
\end{cases}$$

(1) can be easily the extended to the multiple period. Suppose for each individual $i$ who gets treatment, denote the time it gets treatment as $T_i$. We can estimate the (1), in which 
$$S_{it} = 
\begin{cases}
1, \quad D_i = 1 \quad \& t>T_i  \\
0, \quad otherwise
\end{cases}$$

The estimation on $\alpha_4$ is the effect of the policy. 

One issue is, again the correlation of observations within an individual.Use individual-specific intercept or cluster-robust error to solve the issue. Another issue, of course, is the CIA assumption: Is the (timing of) the implementation of the treatment totally random given the covariates? 

We need to find convincing argument on CIA. If we have a good reason to believe that the implementation of the treatment may be affected some unobservable factors that also affects the outcome, we may need to additionally model the implementation of the treatment (just like the self-selection model!)

(The following is purely my personal idea. I do not know whether it is correct or not.)

We can explictely model the $S_{it}$:

$$S_{it} = 1\{\gamma z_{it} + u_{it}>0\}$$
in which $u$ is error term and
$$cov(\epsilon, u)\ne 0$$
Therefore, for an individual $i$, its log-likelihood function is 
$$\ln{pr(y_{i1},.,y_{it},.,S_{i1},.,S_{it},.|x,z)}  $$

Of course this method is complicated in computation. Another good method is instrumental variable.

# Non-Parametric Method: PSM 

The algorithm for doing Non-parametric estimation is super simple:

- For each x value (in the $D=1$ group):
    - estimate $\widehat{E(y_{1t}-y_{0t'}|x,D=1)}\equiv \frac{\sum_{D_i=1,x_i=x}\left(y_{1ti}-y_{0t'i}\right)}{\sum{\left[1_{\left(D_i=1,x_i =x\right)}\right]}}$  
    - estimate $\widehat{E(y_{0t}-y_{0t'}|x,D=0)} \equiv \sum_{D_j=0}{w(x_j,x)\left(y_{0tj}-y_{0t'j}\right)}$, in which $w(x_j,x)$ is weight, which is larger when $x_j$ is closer to $x$.
    
 The estimated ATT is The difference of the above two terms. 
 
In plain words, the non-parametric method wants to do the following. For each $x$:

- Find all the individuals, both in the treatment and control groups, that have the $x$.Among these individuals:

- For each individual $i$ in treatment group, calculate its change from t' to t. denote as $r^1_i(x)$

- For each individual $i$ in control group, calculate its change from t' to t. Denote as $r^0_i(x)$

- We can get the treatment effect for individuals with $x$: $\hat{\gamma}(x) \equiv  \overline{r}^1(x)- \overline{r}^0(x)$

- Finally we can average $\hat{\gamma}(x)$ over $x$ to get the average treatment effect.




# Difference-in-Difference-in-Difference Method 
 
DID requires that the the control group and experiment group have the same time trend (common natural change of target variable.).Sometimes, however, this may not be true, especially when the control group and the experiment group are conceptional different. To illustrate this, suppose that at year $t$, a province A introduced a health policy targeting on <b>ALL</b> the elder people (over 65). Suppose we have the the health data for all-age people at $t_1$ and $t_2$, with $t_1<t<t_2$. We want to evaluate the effect of such policy on elder people's heath.Following the basic idea, we want to see 
$$E(y^1_{A,old,t_2}|x,old)-E(y^0_{A,old,t_2}|x,old)$$
<p>The second is unobservable. Following (2),A (bad) approach is to check 
   $$E(y^1_{A,old,t_2}-y^0_{A,old,t_1}|x,old)- E(y^0_{A,young,t_2}-y^0_{A,young,t_1}|x,young)$$
   This approach relies on the CIA assumption:
    $$ E(y^0_{A,young,t_2}-y^0_{A,young,t_1}|x,young)=E(y^0_{A,old,t_2}-y^0_{A,old,t_1}|x,old)$$
    This is unrealistic: elder people and young people apparently have different trends of health status!</p>
<p>A another (not so bad) approach is to check
    $$E(y^1_{A,old,t_2}-y^0_{A,old,t_1}|x,old)- E(y^0_{B,old,t_2}-y^0_{B,old,t_1}|x,old)$$
  where $E(y^0_{B,old,t_2}-y^0_{B,old,t_1}|x,old)$ is the trend of change for the elder people at province $B$, where there is no such policy.This relies on the CIA assumption:
    $$E(y^0_{B,old,t_2}-y^0_{B,old,t_1}|x,old)=E(y^0_{A,old,t_2}-y^0_{A,old,t_1}|x,old)$$
    This is less unrealistic, but still skeptical: elder people in A may have different natural trend in health status from elder people in B.</p>
<p> To address this, we can impose the following assumption:
    $$E(y^0_{A,young,t_2}-y^0_{A,young,t_1}|x,young)-E(y^0_{A,old,t_2}-y^0_{A,old,t_1}|x,old)$$
    $$=E(y^0_{B,young,t_2}-y^0_{B,young,t_1}|x,young)-E(y^0_{B,old,t_2}-y^0_{B,old,t_1}|x,old)$$
    That is, <b>the difference in the natural trend of health status between elder and young people in province A and B are the same</b>.Given this assumption, we have 
    $$E(y^1_{A,old,t_2}|x,old)-E(y^0_{A,old,t_2}|x,old)$$
    $$=E(y^1_{A,old,t_2}-y^0_{A,old,t_1}|x,old)-E(y^0_{A,old,t_2}-y^0_{A,old,t_1}|x,old)$$
    $$=E(y^1_{A,old,t_2}-y^0_{A,old,t_1}|x,old)+E(y^0_{B,young,t_2}-y^0_{B,young,t_1}|x,young)$$
    $$-E(y^0_{B,old,t_2}-y^0_{B,old,t_1}|x,old)-E(y^0_{A,young,t_2}-y^0_{A,young,t_1}|x,young)$$
Now we construct a linear model based on this framework. </p>

- Denote the $E(y^0_{B,young,t_1}|x,young)$ as $\alpha_1$
- Denote the $E(y^0_{B,young,t_2}|x,young)$ as $\alpha_1+\alpha_2$. $\alpha_2$ is natural trend for young people at province B.
- Denote the $E(y^0_{B,old,t_1}|x,old)$ as $\alpha_1+\alpha_3$, $\alpha_3$ is the difference of the ex-ante heath status between elder and young at B.
- Denote the $E(y^0_{B,old,t_2}|x,old)$ as $\alpha_1+\alpha_3+\alpha_2+\alpha_4$. $\alpha_4$ is the difference between natural trend for young people and the natural trend for elder people at B.
- Denote the $E(y^0_{A,young,t_1}|x,young)$ as $\alpha_1+\alpha_5$. $\alpha_5$ is the across-province difference.
- Denote the $E(y^0_{A,young,t_2}|x,young)$ as $\alpha_1+\alpha_5+\alpha_2+\alpha_6$. $\alpha_6$ measures the difference between the natural trend of young people in A and that of young people in B.
- Denote the $E(y^0_{A,old,t_1}|x,old)$ as $\alpha_1+\alpha_3+\alpha_5+\alpha_7$. $\alpha_7$ indicates the difference between the ex-ante health status between elder and young at A.
- Denote the $E(y^0_{A,old,t_2}|x,old)$ as $\alpha_1+\alpha_3+\alpha_5+\alpha_2+\alpha_6+\alpha_7+\alpha_4$.
- Denote the $E(y^1_{A,old,t_2}|x,old)$ as $\alpha_1+\alpha_3+\alpha_5+\alpha_2+\alpha_6+\alpha_7+\alpha_4+\alpha_8$. $\alpha_8$ is the true effect of the policy

Now it is easy to get:
- $\alpha_2$ appears whenever at $t_2$.Denote $G=1(0)$ as being in $t_2 (t_1)$, then $\alpha_2$ is the coefficient of $G$. 
- $\alpha_3$ appears whenever old. Denote $O=1(0)$ as being old (young), then $\alpha_3$ is the coefficient of $O$.
- $\alpha_4$ appears whenever old at $t_2$. then $\alpha_4$ is the coefficient of $G*O$
- $\alpha_5$ appears whenever at province A. Denote $A=1(0)$ as being in state A (B). Then $\alpha_5$ is the coefficient of $A$.
- $\alpha_6$ appears whenever at province A and $t_2$. then $\alpha_6$ is the coefficient of $A*G$.
- $\alpha_7$ appears whenever at province A and old. Then $\alpha_7$ is the coefficient of $A*O$.
- $\alpha_8$ appears whenever at province A and old and $t_2$.Then $\alpha_8$ is the the coefficient of $A*O*G$.

There we can write the linear regression model based on the above analysis. 