---
title: "Poisson Regression"
output: 
  pdf_document:
     toc: true
     toc_depth: 3
     fig_width: 4.5
     fig_height: 3
     fig_caption: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Basic Model
Sometimes we are dealing with dependent variable that is non-negative integer. For example, number of newly increasing patients(newly got medals, newly born number of children..) in a given time interval or area or population. if the $y$ has the following characteristics:
1. It is about the number of a certain incident over a given time period or area or population..
2. The number of incident is only related to the measurement of time period. or the area, or the population.
3. The number of incident is not correlated to the previous history. 
4. The probability of a single incident is small (rare event).

In the standard ols case we often assume that $y$ is generated from normal distribution (distribution parameter is a function of $x$). However, if the $y$ has the above characteristics and we want to see the effect of $x$ on $y$, it is better to assume that $y$ is generated from poisson distribution, with parameter as a function of $x$.</p>
Specifically we assume that
$$pr(y_i = y|x)= \frac {e^{-\lambda(x_i)} {\lambda(x_i)}^{y_i}}{y_i !}$$
In which 
$$\lambda(x_i)= e^{x'_i\beta} \tag{1}$$
The reason for such a specification is that we want to make sure that $\lambda>0$. We can immediately write down the mle and estimate the $\beta.$. <b>The basic idea here is that, for discrete non-negative dependent variable, it is a good idea to assume the dependent variable are generated from the poisson distribution. </b>

## The interpretation of $\beta$
<p><b>When we make assumption on the data generation process of $y$, we always should make sure that the coefficient is easy to interpret </b>. In standard linear regression framework, the $y$ is generated form a normal distribution with mean $x'_i\beta$, So <b>$\beta$ measure the marginal effect of $x$ on the mean value of $y$ that is generated from the distribution $N(x'\beta, \sigma^2)$</b>. But what is the interpretation of $\beta$ here in poisson regression? </p>
The property of poisson distribution implies that given $x_i$, the expectation of $y_i$, i.e., the average number of incidents, is $\lambda(x'_i \beta)$.( The variance of the $y_i$ is also  $\lambda(x'_i \beta)$ ).since $\lambda(x'\beta)=e^{x'\beta}$,<b> we can interpret the $\beta$ as the effect of a marginal change of $x$ on the percent change of average number of incident (the number of incident is drawn from the poisson distribution with parameter $\lambda(x' \beta)$)</b>

# Poisson Regression with variable exposure
A natural concern about the above model is that, since we are focusing on the number of incidents in a given interval of time (or given amount of population), we should keep such 'unit' as same across individuals. However, in reality this is not always the case. For example, we want to see the determinants of the number of patients of a decease, using city-level data. One concern is that, a city with larger population tends to have more patients (given other thing same). Also, cities with longer investigation interval tends to have more patients. Therefore we want to incorporate the 'unit' or 'Exposure'$T_i$ into our model.i.e., 
$$\lambda_i = exp(x'_i\beta)T_i$$
This implies that given $x'_i$, the average amount of incident is proportion to the 'exposure' (e.g., the total population , total total area, the time interval...).

# Negative Binominal Regression
As was mentioned,the baseline dependent variable data generation process simply implies $E(y_i|x_i)=exp(x'_i\beta)=var(y_i|x_i)$. This may not be consistent with data: After all, we cannot make sure that our data has variance equal to expectation. If the variance of $y$ is obvious higher than its mean, then we have to modify the (1) to allow for more variance.
<p>A natural way to realize this is to 
    $$\log{\lambda_i}= x'_i \beta + \epsilon$$
</p>
in which $\epsilon$ is unobservable disturbance. Denote $v_i= e^{\epsilon}$. we immediately have
$$pr(y_i |x,v_i)= \frac {e^{-e^{ x'_i \beta}v_i} {\left(e^{ x'_i \beta}v_i\right)}^{y_i}}{y_i !} $$
of course we cannot directly apply MLE to this expression, since the $v_i$ is unobersable. We already know that a common way of getting rid of such term is to do integration w.r.t $v_i$
$$pr(y_i |x)=\int{pr(y_i |x,v_i)f(v_i)dv_i}=\int{\frac {e^{-e^{ x'_i \beta}v_i} {\left(e^{ x'_i \beta}v_i\right)}^{y_i}}{y_i !}f(v_i)dv_i}$$
This is easy to  solve if we assume $v_i$ follows $Gamma$ distribution (Show details!)

# Truncated Poisson Regression
Please see the notes of 'missing and censored dependent variable' for more detailed information on basic truncated regression. Sometimes, we may also faced with truncated dependent variables.<b> An example is studying the determinants of the weekly shopping times, which is a variable that can only take non-negative variable (0,1,2,..) and is a natural case for doing poisson regression. But, what if we collect the data at the shopping mall? people going to shopping mall always has positive shopping times! As a result, the data we collect is truncated at $y=0$, i.e., we cannot observe any information of those people who does not go to the shopping small.</b>
<p>As usual, we use MLE to estimate. Following the notes on 'missing and censored dependent variable',the likelihood function for an individual is now:
$$pr(y=y_i| y_i>0 )=\frac{f(y=y_i,y_i>0)}{pr(y_i>0)}=\frac{e^{-\lambda}\lambda^y}{y!(1-e^{-\lambda})} $$

# Zero-Inflated Poisson Regression (ZIP)
<p>Sometimes, there may be too many $y=0$ individuals in the sample. <b>Recall the cragg hurdle model, where people first make choices on whether or not to participate. For those to participate, they makes on amount. Such setting is more flexible, since it allows that the mechanism that determines whether an individual participate or not differs from the mechanism that determines the amount to choose.</b> </p>
Following such a logic, we can make the following model specification:
$$y_i = \begin{cases}
y^*_i \ge 1,\quad w_i =1 \\
0, \quad w_i=0 \\
\end{cases}
$$
and we assume that $y^*_i$ is generated from a poisson distribution, but $y^*_i$ has to be positive. Therefore, $y^*_i$ in fact comes from a poisson distribution truncated at 0. Therefore we can write the data generation process of $y^*_i$ is 
$$pr(y=y^*_i|x_i) =\frac {e^{-\lambda(x_i)} {\lambda(x_i)}^{y_i}}{y_i !(1-e^{-\lambda(x_i)})} $$
and 
$$
w_i = \begin{cases}
1, \quad z'_i \gamma +v_i>0 \\
0, \quad z'_i \gamma+ v_i<0
\end{cases}
$$
Therefore for an individual with $w_i=0$, the likelihood function is 
$$pr(w_i=0)= pr(v_i<-z'_i \gamma)$$
for an individual with $w_i=0$, the likelihood function is
$$pr(y=y^*_i,w_i=0|x_i)=pr(v_i>-z'_i \gamma)*\frac {e^{-\lambda(x_i)} {\lambda(x_i)}^{y_i}}{y_i !(1-e^{-\lambda(x_i)})} $$
The equation holds since $v_i$ is independent of the distribution of $y^*_i$. Therefore, the likelihood function for an individual $i$ is 
$${\left[pr(v_i<-z'_i \gamma)\right]}^{1-w_i}{\left[pr(v_i>-z'_i \gamma)*\frac {e^{-\lambda(x_i)} {\lambda(x_i)}^{y_i}}{y_i !(1-e^{-\lambda(x_i)})}\right]}^{w_i}$$
How to choose from ZIP or standard poisson regression? Vuong statistics.